* About
This is just a website for me and anyone who happens to stumble upon it. I find
that most of my thoughts don't go very far in terms of the time that I put into
them. This page is just an opportunity for me to put some more energy into those
thoughts, perhaps that generates more thoughts that make me smarter. That's the
aim right?
I am a:
- Failed chemical engineering student
- Slightly less failed software engineering student
- Optimist

* Album Review: Draining Love Story <2021-03-29 Mon 20:29>
Draining love story is an album by Sewerslvt (pronounced sewer slut) which is a
combination of drum and bass with atmospheric and even orchestral tones in later
tracks like /slowdeath/. Perhaps the most popular of the songs on the album is
the song /Newlove/ which garnered Sewerslvt's a lot of love.
Part of what I love about this album is the experimentation with vocals which
reminds me a lot of how /Ecco2k/ chops and skews his own in the album /E/, some
of these vocals can be found on /Lexapro Delirium/ and /Slowdeath/ . Some
of this album seems like catharsis in songs like /Ecifircas/ where the
introduction quotes a movie on the theme of reposition and needless
suffering. Sewerslvt isn't afraid to play with ambient sounds either as several
of the songs feature long preludes and endings with simply ambient sounds. 
Although some of the drum loops can get a bit repetitive across songs
I find myself coming back to this album several times to give it a another
listen. Thanks for making music!

* Hopecore <2021-03-27 Sat 22:29>
I'm going to defining another music genre called /hopecore/. This is a label for
music that gives an overwhelming appreciation for life or just steps you out of
your body for a bit so that you can appreciate everything that's going on around
you. This music is typically found on a loud bus using an overkill DAP for
wireless earbuds that don't deserve the device that they are connected to. Most
of these songs will be electronic or leftfield because that's simply what I'm
into

Here's the list (I'll keep it updated as I find more):
- [[https://www.youtube.com/watch?v=mK6uANkwyW4][Sewerslvt - Slowdeath]]
- [[https://www.youtube.com/watch?v=sayaJaLbv_o][Whitearmor - Frutta E verdura]]
- [[https://www.youtube.com/watch?v=-LgYzva-xq8][Aphex Twin - Avril 14th]]
- [[https://www.youtube.com/watch?v=FBwwV8iEJH4][Neat Beats - Sept coups de feu]]
- [[https://www.youtube.com/watch?v=rKsb71ALRvo][Ecco2k - Time]]

** How I find music
While I'm at it I might as well go over how I find music like this. The way that
I collect music has been described by my friends much 'like how a deep sea
vessel nets the ocean'. This is astoundingly accurate. I have a variety of
private trackers (my ocean fleet) and I enter any genre tags that I like (my
net) and then go on to download everything that I can find in various collages
that has interesting album art (the catch). I have over 1TB of music that I
haven't listened to, but at least it makes a very interesting shuffle.

** Gear
- DAP
  - Hiby R3 Pro
  - iPhone SE (2016)
- IEM
  - Moondrop Blessing 2
  - Moondrop Starfields
  - Jabra Elite 65t
